### ISSUE TITLE
Keyboard shortcuts and more

### ISSUE THREAD

**Issue by ervinDuck** [TolikPylypchuk/KeyboardSwitch#78]
Hello! Firstly, I have to thank you for your app being very helpful to me! I use it on both my Mac and Linux.

However, the keyboard shortcuts seem a little awkward to me. For example, it would be much more convenient for me to switch the layout by double-pressing the Shift key. It is also not entirely clear why, if no text is selected and a key combination is pressed, the modified text from the clipboard is pasted; this is often not very convenient as well.

Is there any possibility to change the above?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for using the app, I really appreciate your feedback!

Regarding double-pressing the Shift key - when I thought about possible key combinations for triggering the switch, I thought that just one key would be a little too destructive since it would be too easy to press it by accident. You're not the first person to ask about it though. I'm not currently actively working on this application, but I'm planning on revisiting it in the coming months, so I'll add this possibility.

Regarding the second point - yeah, it's not convenient, but there isn't much I can do about it. In order to switch text, the app does some the following actions:

- Simulates pressing `Ctrl+C` to copy text.
- Gets the text from the clipboard.
- Transforms the text and puts it into the clipboard.
- Simulates pressing `Ctrl+V` to paste the text.

So, if there is no selected text, the following happens:

- The app simulates pressing `Ctrl+C` and it does nothing.
- The app gets the text that was previously in the clipboard.
- The app transforms the text and puts it into the clipboard.
- The app simulates pressing `Ctrl+V` to paste the transformed text.

This is how you end up with garbage text. There isn't anything I can do about it currently. The app has no way of knowing whether pressing `Ctrl+C` actually copied any text and so it doesn't know whether the text should be transformed. I've looked at other ways to implement the app functionality, but currently this is the only way I could achieve that.

**Comment by ervinDuck** [comment]
Thank a lot!

**Comment by TolikPylypchuk** [comment]
Hi @ervinDuck! I've finally implemented the ability to use a single modifier key to trigger switching. It will be available in version 4.2 which I will hopefully release soon.

**Comment by TolikPylypchuk** [comment]
I've finally released version 4.2.0 which implements this feature. Sorry for the delay, but there were many other changes there as well.
